name: Node.js Package

on:
  push:
    branches:
      - release
      - master
      - dev
    tags:
      - "v*"

  pull_request:
    branches:
      - release
      - master
      - dev

  release:
    types: [created, published]
    
jobs:
  build:
    runs-on: ubuntu-24.04
    environment: envdev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: CI=false npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: node-app-artifact-${{ github.run_number }}
          path: build/       # <-- Change to your actual output folder

  deploy:
    runs-on: ubuntu-24.04
    environment: envdev
    
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: node-app-artifact-${{ github.run_number }}
          path: ./artifact-files

      - name: Show downloaded files
        run: ls -R ./artifact-files


      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy build files to EC2 server
        run: |
          scp -i ~/.ssh/deploy-key.pem -r ./artifact-files/* \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

      - name: Restart app on EC2
        run: |
          ssh -i ~/.ssh/deploy-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo systemctl restart apache2"
          "sudo systemctl status apache2"




